definitions:
  schema.AuthReq:
    properties:
      decrypt_data:
        type: string
      user_account:
        type: string
    required:
    - decrypt_data
    - user_account
    type: object
  schema.AuthResp:
    properties:
      code:
        type: integer
      msg:
        type: string
      token:
        type: string
    type: object
  schema.CommResp:
    properties:
      code:
        type: integer
      msg:
        type: string
    type: object
  schema.CreateDpReq:
    properties:
      audio_link:
        type: string
      content:
        type: string
      dp_name:
        type: string
      image_link:
        type: string
      tone_link:
        type: string
    required:
    - audio_link
    - content
    - dp_name
    - image_link
    - tone_link
    type: object
  schema.CreateResourceReq:
    properties:
      is_png:
        type: boolean
      resource_describe:
        type: string
      resource_type:
        type: string
    required:
    - resource_describe
    - resource_type
    type: object
  schema.CreateResourceResp:
    properties:
      code:
        type: integer
      msg:
        type: string
      resource_link:
        type: string
    type: object
  schema.DpEntity:
    properties:
      cover_image_link:
        type: string
      create_time:
        type: string
      dp_link:
        type: string
      dp_name:
        type: string
      dp_status:
        type: integer
      hot_score:
        type: integer
      owner:
        type: string
      update_time:
        type: string
    type: object
  schema.GetDpResp:
    properties:
      code:
        type: integer
      data:
        items:
          $ref: '#/definitions/schema.DpEntity'
        type: array
      msg:
        type: string
    type: object
  schema.GetResourceResp:
    properties:
      code:
        type: integer
      data:
        items:
          $ref: '#/definitions/schema.ResourceEntity'
        type: array
      msg:
        type: string
    type: object
  schema.PubKeyResp:
    properties:
      code:
        type: integer
      data:
        type: string
      msg:
        type: string
    type: object
  schema.RegisterReq:
    properties:
      decrypt_data:
        type: string
      user_account:
        type: string
      user_name:
        type: string
    required:
    - decrypt_data
    - user_account
    - user_name
    type: object
  schema.ResourceEntity:
    properties:
      cover_image_link:
        type: string
      create_time:
        type: string
      resouce_id:
        type: string
      resource_describe:
        type: string
      resource_link:
        type: string
      update_time:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: rliu
    url: http://www.swagger.io/support
  description: 榕树平台API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: cc fintech practices API
  version: "1.0"
paths:
  /{file_type}/{file_name}:
    get:
      consumes:
      - application/json
      description: 下载文件的统一接口，数字人、封面图片、素材库素材均通过本接口下载
      parameters:
      - description: 下载的文件类型, 类型为枚举值：dp、resource、cover_image
        in: path
        name: file_type
        required: true
        type: string
      - description: 下载的文件名称
        in: path
        name: file_name
        required: true
        type: string
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - '*/*'
      responses:
        "200":
          description: OK
          schema:
            type: file
      summary: 下载文件接口
      tags:
      - download
    post:
      consumes:
      - application/json
      description: 上传文件的统一接口，数字人、封面图片、素材库素材均通过本接口下载
      parameters:
      - description: 上传的文件类型，类型为枚举值：audio、resource
        in: path
        name: file_type
        required: true
        type: string
      - description: 上传的文件名称，需要带上相应后缀，例如audio为.wav, resource为 .png 或 .mp4
        in: path
        name: file_name
        required: true
        type: string
      - description: 上传的文件
        in: formData
        name: file
        required: true
        type: file
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - '*/*'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.CommResp'
      summary: 上传文件接口
      tags:
      - download
  /dp:
    get:
      consumes:
      - application/json
      description: 查询用户所拥有的数字人信息
      parameters:
      - description: 分页查询页数，默认为1
        in: query
        name: page_no
        type: integer
      - description: 分页查询页大小，默认为10
        in: query
        name: page_size
        type: integer
      - description: 查询返回的排序字段，默认为创建时间
        in: query
        name: order_field
        type: string
      - description: 排序方式，默认为倒序
        in: query
        name: method
        type: string
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.GetDpResp'
      summary: 查询数字人接口
      tags:
      - digital person
    post:
      consumes:
      - application/json
      description: 创建用户数字人信息
      parameters:
      - description: 数字人名称、形象link、音频link、音色link、文本内容。如传输音频link，则音色link与文本内容可为空字符串。如音频link为空字符串，则后二者必须传输
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/schema.CreateDpReq'
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.CommResp'
      summary: 创建数字人接口
      tags:
      - digital person
  /dp/{dp_link}:
    delete:
      consumes:
      - application/json
      description: 删除用户所拥有的数字人信息
      parameters:
      - description: 需删除的数字人id
        in: path
        name: dp_link
        required: true
        type: string
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.CommResp'
      summary: 删除数字人接口
      tags:
      - digital person
  /login:
    post:
      consumes:
      - application/json
      description: 登录以获取token
      parameters:
      - description: 用户账号与加密的用户密码
        in: body
        name: user_account
        required: true
        schema:
          $ref: '#/definitions/schema.AuthReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.AuthResp'
      summary: 登录接口
      tags:
      - user
  /pubkey:
    get:
      consumes:
      - application/json
      description: 获取rsa公钥
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.PubKeyResp'
      summary: 获取公钥接口
      tags:
      - authorization
  /register:
    post:
      consumes:
      - application/json
      description: 注册用户
      parameters:
      - description: 用户名称、用户账户与加密的用户密码
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/schema.RegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.CommResp'
      summary: 注册用户接口
      tags:
      - user
  /resource:
    post:
      consumes:
      - application/json
      description: 创建用户素材库素材
      parameters:
      - description: 素材描述、素材类型(tone、image)， IsPng(如果是image类型，是否是图片形象素材)
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/schema.CreateResourceReq'
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.CreateResourceResp'
      summary: 创建素材库素材接口
      tags:
      - resource lib
  /resource/{resource_link}:
    delete:
      consumes:
      - application/json
      description: 删除用户所拥有的素材库素材
      parameters:
      - description: 素材连接，tone or image
        in: path
        name: resource_link
        required: true
        type: string
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.CommResp'
      summary: 删除素材库素材接口
      tags:
      - resource lib
  /resource/{resource_type}:
    get:
      consumes:
      - application/json
      description: 查询用户所拥有的 or 公共的素材库素材信息
      parameters:
      - description: 素材类型，tone or image
        in: path
        name: resource_type
        required: true
        type: string
      - description: 分页查询页数，默认为1
        in: query
        name: page_no
        type: integer
      - description: 分页查询页大小，默认为10
        in: query
        name: page_size
        type: integer
      - description: 是否查询公共素材，默认为否
        in: query
        name: is_public
        type: boolean
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.GetResourceResp'
      summary: 查询素材库接口
      tags:
      - resource lib
swagger: "2.0"
